### ISSUE TITLE
Error running in net7.0 VS 2022 17.6.3

### ISSUE THREAD

**Issue by Jothay** [RdJNL/TextTemplatingCore#12]
## VS+Extension info
Microsoft Visual Studio Enterprise 2022
Version 17.6.3
VisualStudio.17.Release/17.6.3+33801.468
Microsoft .NET Framework
Version 4.8.09032

Text Templating File Generator .NET 6 v1.2.0

## RunAll.tt
```
<#@ template hostSpecific="true" language="C#" debug="true"
#><#@ output extension=".cstxt"
#><#@ assembly name="mscorlib"
#><#@ assembly name="System"
#><#@ assembly name="System.ComponentModel"
#><#@ assembly name="System.ComponentModel.DataAnnotations"
#><#@ assembly name="System.Private.Xml"
#><#@ assembly name="System.Xml.ReaderWriter"
#><#@ assembly name="System.Xml.Linq"
#><#@ assembly name="$(UserProfile)\.nuget\packages\microsoft.visualstudio.texttemplating\17.5.33428.366\lib\net472\Microsoft.VisualStudio.TextTemplating.dll"
#><#@ assembly name="$(UserProfile)\.nuget\packages\Microsoft.VisualStudio.Interop\17.6.36389\lib\net6.0\Microsoft.VisualStudio.Interop.dll"
#><#@ assembly name="$(UserProfile)\.nuget\packages\microsoft.visualstudio.texttemplating.interfaces\17.5.33428.366\lib\net472\Microsoft.VisualStudio.TextTemplating.Interfaces.dll"
#><#@ assembly name="$(UserProfile)\.nuget\packages\microsoft.visualstudio.texttemplating.interfaces.15.0\16.10.31320.204\lib\net45\Microsoft.VisualStudio.TextTemplating.Interfaces.15.0.dll"
#><#@ assembly name="$(SolutionDir)Core\MyProject.T4s\bin\Debug\net7.0\MyProject.T4s.dll"
#><#@ import namespace="System"
#><#@ import namespace="System.CodeDom.Compiler"
#><#@ import namespace="System.Collections.Generic"
#><#@ import namespace="System.ComponentModel.DataAnnotations"
#><#@ import namespace="System.Configuration"
#><#@ import namespace="System.Diagnostics"
#><#@ import namespace="System.IO"
#><#@ import namespace="System.Linq"
#><#@ import namespace="System.Linq.Expressions"
#><#@ import namespace="System.Reflection"
#><#@ import namespace="System.Runtime.Serialization"
#><#@ import namespace="System.Text"
#><#@ import namespace="System.Text.RegularExpressions"
#><#@ import namespace="System.Xml"
#><#@ import namespace="MyProject.T4s"
#><#
void SaveOutputNoDot(string typeName, string fileNameModifier)
{
    if (!string.IsNullOrWhiteSpace(typeName)) { fileNameModifier = typeName + fileNameModifier; }
    var templateDirectory = Path.GetDirectoryName(this.Host.TemplateFile);
    var outputFilePath = Path.Combine(templateDirectory, fileNameModifier);
    if (fileNameModifier.Contains("\\"))
    {
        var dirs = fileNameModifier.Split(new[] { '\\' }, StringSplitOptions.RemoveEmptyEntries);
        var builtPath = string.Empty;
        for (var i = 0; i < dirs.Length - 1; i++)
        {
            builtPath += (builtPath == string.Empty ? string.Empty : "\\") + dirs[i];
            var tempDirPath = Path.Combine(templateDirectory, builtPath);
            if (!Directory.Exists(tempDirPath))
            {
                Directory.CreateDirectory(tempDirPath);
            }
        }
    }
    System.IO.File.WriteAllText(outputFilePath, this.GenerationEnvironment.ToString());
    this.GenerationEnvironment = new StringBuilder();
}
var g = new MyGenerator();
g.Execute(
    writeFn: content => Write(content),
    saveFn: name => SaveOutputNoDot(name, string.Empty));
```

I get 2 errors:
(97,70): error CS0234: The type or namespace name 'ITextTemplatingEngineHost' does not exist in the namespace 'Microsoft.VisualStudio.TextTemplating' (are you missing an assembly reference?)
(101,63): error CS0234: The type or namespace name 'ITextTemplatingEngineHost' does not exist in the namespace 'Microsoft.VisualStudio.TextTemplating' (are you missing an assembly reference?)

However, my T4 file is less than 80 lines long, so it's not the T4 file itself. Double-clicking the errors don't point to any spot in my solution (or does anything afaict).

If I remove the Microsoft.VisualStudio.* dll assemblies, I get the following error:
Something went wrong executing the template in .NET Core: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Interop, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.Interop, Culture=neutral, PublicKeyToken=null'
```
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at RdJNL.TemplateExecute.LibraryLoadContext.LoadLibrary(String library) in D:\Dev\Projects\TextTemplatingCore\TemplateExecute\LibraryLoadContext.cs:line 28
   at RdJNL.TemplateExecute.Program.Main(String[] args) in D:\Dev\Projects\TextTemplatingCore\TemplateExecute\Program.cs:line 66
```

**Comment by Jothay** [comment]
I found this as it may be relevant: https://stackoverflow.com/questions/74367760/could-not-load-file-or-assembly-system-runtime-version-7-0-0-0-after-ins

**Comment by RdJNL** [comment]
You don't need to add those VisualStudio assemblies and you also shouldn't need mscorlib and the System assemblies. So try removing those.

It also seems the MyProject.T4s.dll you're referencing is a .NET 7 project and the extension doesn't support .NET 7 yet. So that might be the issue (but I'm not 100% sure). I'll fix this soon.

**Comment by RdJNL** [comment]
I've done a bit more research and I'm now running into the issue discussed in the stackoverflow link. To be continued...

**Comment by Jothay** [comment]
Thanks for looking into it, and if you need me to try anything specific on my end, I'm happy to.

**Comment by RdJNL** [comment]
I've created a new version running .NET 8 that should resolve this issue.
