### ISSUE TITLE
Could not load file or assembly Microsoft.VisualStudio.Interop.dll

### ISSUE THREAD

**Issue by Craigoss** [RdJNL/TextTemplatingCore#17]
We recently migrated from .net framework 4.8 to .net 6. We've found our existing .tt files do not generate.

We have added this extension and attempted to run but get the following errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Something went wrong executing the template in .NET Core: System.IO.FileNotFoundException: Could not load file or assembly 'd:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\Microsoft.VisualStudio.Interop.dll'. The system cannot find the file specified.
File name: 'd:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\Microsoft.VisualStudio.Interop.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at RdJNL.TemplateExecute.LibraryLoadContext.LoadLibrary(String library) in C:\Dev\TextTemplatingCore\TemplateExecute\LibraryLoadContext.cs:line 24
   at RdJNL.TemplateExecute.Program.Main(String[] args) in C:\Dev\TextTemplatingCore\TemplateExecute\Program.cs:line 68	Hvcc.Ips.Host	d:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\Entities.tt	1

I did manage to find a package to obtain the Microsoft.VisualStudio.Interop.dll, but then found it needed to be copied into several places in our solution. Which then gave us a new error below:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Something went wrong executing the template in .NET Core: System.IO.FileNotFoundException: Could not load file or assembly 'd:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\%VSAPPIDDIR%EntityFramework.dll'. The system cannot find the file specified.
File name: 'd:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\%VSAPPIDDIR%EntityFramework.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at RdJNL.TemplateExecute.LibraryLoadContext.LoadLibrary(String library) in C:\Dev\TextTemplatingCore\TemplateExecute\LibraryLoadContext.cs:line 24
   at RdJNL.TemplateExecute.Program.Main(String[] args) in C:\Dev\TextTemplatingCore\TemplateExecute\Program.cs:line 68	Hvcc.Ips.Host	d:\Repos\Hvcc.Ips\Src\Server\Hvcc.Ips.Host\Entities\Autogenerated\Entities.tt	1	

Any ideas?

Thanks,
Craig.

**Comment by RdJNL** [comment]
What assembly references do you have in the T4 file?

**Comment by chammonsvusion** [comment]
Also having simular issue.  I'm migrating from framework 4.6.1 to net6.0 and found your extension.  I get an error when running one of my templates ..

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Something went wrong executing the template in .NET Core: System.IO.FileNotFoundException: Could not load file or assembly 'C:\src\vusionpackages-core\Shakespeare.Data\System.Xml.dll'. The system cannot find the file specified.
File name: 'C:\src\vusionpackages-core\Shakespeare.Data\System.Xml.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at RdJNL.TemplateExecute.LibraryLoadContext.LoadLibrary(String library) in C:\Dev\TextTemplatingCore\TemplateExecute\LibraryLoadContext.cs:line 24
   at RdJNL.TemplateExecute.Program.Main(String[] args) in C:\Dev\TextTemplatingCore\TemplateExecute\Program.cs:line 68	Shakespeare.Data	C:\src\vusionpackages-core\Shakespeare.Data\AgentRunTemplate_GENERATED.tt	1	
```

I am referencing several of my own assemblies and several system ones including system.xml.dll
`<#@ assembly Name="System.Xml.dll" #>`

This assembly should be in the GAC .. not 'C:\src\vusionpackages-core\Shakespeare.Data' (which is not even the output folder of my project).

**Comment by RdJNL** [comment]
If the assembly name ends in `.dll`, the tool will assume it's a path (either absolute or relative to the template).

.NET 6 does not have a GAC, so that's not gonna work. I don't think you should need a System.Xml assembly at all, TBH. I think it's included in the .NET 6 runtime by default.

**Comment by ZTHawk** [comment]
I have the same issue but with NET 8.
Here is a sample project: 

### LibToLoad:
```
namespace LibToLoad
{
    public abstract class BaseClass { }
    public partial class MyClass1 : BaseClass
    {
        public System.Guid Uid;
    }
}
```

### T4 file:
```
<#@ template language="C#" debug="false" hostspecific="false" #>
<#@ output extension=".g.cs"#>
<#@ include file="EF6.Utility.CS.ttinclude" #>
<#@ assembly name="$(SolutionDir)LibToLoad\bin\Debug\net8.0\LibToLoad.dll" #> 
<#
    var code = new CodeGenerationTools(this);
    var baseType = typeof(LibToLoad.BaseClass);
    var asmQN = baseType.AssemblyQualifiedName;
#>
```
